version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - HOST=0.0.0.0
    command: sh -c "npm install && npm run dev"

volumes:
  node_modules:
